version: '3.3'

services:
  db:
    image: mariadb:10.3.3
    environment:
      MYSQL_ROOT_PASSWORD: lisk6532root
      MYSQL_USER: lisk
      MYSQL_PASSWORD: lisk6532
      MYSQL_DATABASE: lisk
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.7-1
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: lisk6532root
      MYSQL_USER: lisk
      MYSQL_PASSWORD: lisk6532
    ports:
      - 8181:80
  api:
    image: io.lisk/api:04e47ce
    environment:
      DB_URL: db:3306
      DB_NAME: lisk
      DB_USER: lisk
      DB_PASSWORD: lisk6532
    links:
      - db
    ports:
      - 8080:8080