db:
  image: mariadb:10.3.3
  environment:
    MYSQL_ROOT_PASSWORD: lisk6532root
    MYSQL_USER: lisk
    MYSQL_PASSWORD: lisk6532
    MYSQL_DATABASE: lisk
  ports:
    - 8182:3306
phpmyadmin:
  image: phpmyadmin/phpmyadmin:4.7.7-1
  links:
    - db
  environment:
    PMA_HOST: db
    PMA_PORT: 3306
    MYSQL_ROOT_PASSWORD: lisk6532root
    MYSQL_USER: lisk
    MYSQL_PASSWORD: lisk6532
  ports:
    - 8181:80