version: '3.3'

services:
  lisk-web:
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
